In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from scipy import stats
from sklearn.linear_model import LinearRegression

In [2]:
customers = pd.read_csv(r"E:\projects\brazilian e-commerce public dataset by olist\olist_customers_dataset.csv")
geolocation = pd.read_csv(r"E:\projects\brazilian e-commerce public dataset by olist\olist_geolocation_dataset.csv")
order_items = pd.read_csv(r"E:\projects\brazilian e-commerce public dataset by olist\olist_order_items_dataset.csv")
order_payments = pd.read_csv(r"E:\projects\brazilian e-commerce public dataset by olist\olist_order_payments_dataset.csv")
order_reviews = pd.read_csv(r"E:\projects\brazilian e-commerce public dataset by olist\olist_order_reviews_dataset.csv")
orders = pd.read_csv(r"E:\projects\brazilian e-commerce public dataset by olist\olist_orders_dataset.csv")
products = pd.read_csv(r"E:\projects\brazilian e-commerce public dataset by olist\olist_products_dataset.csv")
sallers = pd.read_csv(r"E:\projects\brazilian e-commerce public dataset by olist\olist_sellers_dataset.csv")
products_category = pd.read_csv(r"E:\projects\brazilian e-commerce public dataset by olist\product_category_name_translation.csv")

# Section 1: Data Exploration

## Orders (DIMENSION TABLE)

#### 1. number of rows and columns
###### order.shape
#### 2. first 5 rows
###### orders.head
#### 3. column's names
###### orders.columns
#### 4. data types
###### orders.dtype
#### 5. data preview
###### orders.info()
#### 6. perecent of missing values
###### (orders.isna().sum()/len(orders))*100
#### 7. number of duplicates
###### orders.duplicated().sum()
#### 8. data numeric describtion
###### orders.describe()
#### 9. data string describtion
###### orders.describe(include = "object")

In [3]:
## 1. number of rows and columns
orders.shape

(99441, 8)

In [4]:
## 2. first 5 rows
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [5]:
## order_purchase_timestamp ---> "وقت الشراء : اللحظة الي العميل داس فيها علي زرار "شراء 
## فايدته : اعرف منه ذروة المبيعات انهي ايام في الاسبوع بتجيب مبيعات اكثر؟
##  وانهي ساعات في اليوم

## order_approved_at ---> وقت الموافقة علي الدفع: اللحظة الي البنك او بوابة الدفع
## وافقت فيها علي المعانلة المالية
## فايدته: لو طرحته من وقت الشراء هعرف الدفع بياخد وقت قد اية عشان يتأكد

## order_delivered_carrier_date ---> وقت ما التاجر يسلم الشحنة لشركة الشحن: 
## اللحظة الي التاجر سلم فيها المنتج لشركة الشحن 
## فايدته: بيقيس كفاءة التاجر وسرعته في التجهيز 

## order_delivered_customer_date ---> وقت وصول الشحنة للعميل:
##  اللحظة الفعلية الي العميل استلم فيها الشحنة في بيته 
## فايدته : دة اهم عمود لقياس تجربة العميل total delivery time

## order_estimated_delivery_date ---> تاريخ التوصيل المتوقع: التريخ الي موقع olist 
## توقعه ووعد بيه العميل وقت الشراء ان الشحنة هتوصل فيه

In [6]:
## 3. columns name
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

##### order_id -----> primary column
##### customer_id -----> foreign key

In [7]:
## 4. orders data types
orders.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

### Need data type conversion
###### order_purchase_timestamp
###### order_approved_at
###### order_delivered_carrier_date
###### order_delivered_customer_date
###### order_estimated_delivery_date

In [8]:
## 5. data preview
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [9]:
## 6. perecent of missing values
(orders.isna().sum()/len(orders))*100

order_id                         0.000000
customer_id                      0.000000
order_status                     0.000000
order_purchase_timestamp         0.000000
order_approved_at                0.160899
order_delivered_carrier_date     1.793023
order_delivered_customer_date    2.981668
order_estimated_delivery_date    0.000000
dtype: float64

In [10]:
## understand null values

In [11]:
orders[orders["order_delivered_customer_date"].isna()]["order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [ ]:
## investigated missing delivery dates by checking order statues distribution.
## missing values were mostly linked to non-delivered states (shipped, canceled, unavailable),
## indicating business logic rather than data quality issues.
## keeping these nulls is important 
## because removing them would distore the real order lifecycle and lead to biased delivery performance analysis
## why keep them?
## perserves full order journey (including canceled and in progress orders),
## which is essential for funnel and operational analysis

In [12]:
orders[orders["order_delivered_carrier_date"].isna()]["order_status"].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [ ]:
## analyzed missing carrier delivery dates against order status.
## Most null values belonged to orders that never reached shipping stages,
## so missingness was considered expected.
## dropping these nulls would remove early-stage orders and break visiblity into the full fullfillment pipline.
## why keep them?
## helps maintain accurate view of order progression and allows proper segmentation between pre-shipping 
## and post-shipping stages

In [13]:
orders[orders["order_approved_at"].isna()]["order_status"].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [ ]:
## checked missing approvel timestamps using order status distribution.
## missing values were mainly associated with canceled or early stage orders,
## while a few delivered orders were flagged for review.
## keeping these nulls avoids artificially inflating approval rates and preserves accuracy in order processing analysis
## why keep them?
## ensures correct calculation of approval kpis and prevents misleading insights about operational efficiency.

In [14]:
## 8. number of duplicates
orders.duplicated().sum()

np.int64(0)

In [15]:
## 9. data numeric describtion
orders.describe()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-03-31 15:08:21,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

In [16]:
## 10. orders_id unique or not
orders["order_id"].is_unique

True

In [17]:
## DIMENSION TABLE
## order_id PRIMARY key
## customer_id foreign key

____________________________________________________________

## order_items (FACT TABLE)

In [18]:
## 1. number of rows and columns
order_items.shape

(112650, 7)

In [19]:
## 2. first 5 rows
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

### order_items table is the master table (fact table)

###### order_item_id -----> primary key
###### order_id -----> foriegn key
###### product_id -----> foriegn key
###### seller_id ------> foriegn key

In [20]:
## 3. columns name
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

In [21]:
## 4. orders_item data types
order_items.dtypes

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

In [22]:
## need data type conversion
## shipping_limit_date

In [23]:
## 5. data preview
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [24]:
#### no missing values

In [25]:
## 6. number of duplicates
order_items.duplicated().sum()

np.int64(0)

In [26]:
##### no duplicates

In [27]:
## 7. data numeric describtion
order_items.describe()

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [28]:
## 10. orders_id unique or not
order_items["order_item_id"].is_unique

False

In [29]:
order_items["order_id"].is_unique

False

In [30]:
top_duplicates_order_items = order_items["order_item_id"].value_counts().index[0]
order_items[order_items["order_item_id"]==top_duplicates_order_items]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

____________________________________________________________

## order_payments (FACT TABLE)

In [31]:
### 1. number of rows and columns
order_payments.shape

(103886, 5)

In [32]:
### 2. first 5 rows
order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [33]:
### 3. column's names
order_payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='str')

In [34]:
## FACT TABLE

In [35]:
### 4. data types
order_payments.dtypes

order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

In [36]:
### 5. data preview
order_payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [37]:
## no nulls

In [38]:
### 6. number of duplicates
order_payments.duplicated().sum()

np.int64(0)

In [39]:
### 7. data numeric describtion
order_payments.describe()

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

In [40]:
## 10. orders_id unique or not
order_payments["order_id"].is_unique

False

_____________________________________________________________

## order_reviews (FACT TABLE)

In [41]:
### 1. number of rows and columns
order_reviews.shape

(99224, 7)

In [42]:
### 2. first 5 rows
order_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [43]:
## FACT TABLE
## order_id -----> foriegn key

In [44]:
### 3. column's names
order_reviews.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='str')

In [45]:
### 4. data types
order_reviews.dtypes

review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

In [46]:
## review_creation_date  ----> dtype need change      
## review_answer_timestamp ----> dtype need change

In [47]:
### 5. data preview
order_reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

In [48]:
## 6. perecent of missing values
(order_reviews.isna().sum()/len(order_reviews))*100

review_id                   0.000000
order_id                    0.000000
review_score                0.000000
review_comment_title       88.341530
review_comment_message     58.702532
review_creation_date        0.000000
review_answer_timestamp     0.000000
dtype: float64

In [49]:
## replace null values

In [50]:
## 7. number of duplicates
order_reviews.duplicated().sum()

np.int64(0)

In [51]:
## 8. data numeric describtion
order_reviews.describe()

       review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

In [52]:
## 10. orders_id unique or not
order_reviews["review_id"].is_unique

False

In [53]:
top_duplicates_review = order_reviews["review_id"].value_counts().index[0]
order_reviews[order_reviews['review_id']== top_duplicates_review]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
2952,c444278834184f72b1484dfe47de7f97,df56136b8031ecd28e200bb18e6ddb2e,5,NaN,NaN,2017-02-08 00:00:00,2017-02-14 13:58:48
43897,c444278834184f72b1484dfe47de7f97,566f53fc7d36fa366f7e221468121877,5,NaN,NaN,2017-02-08 00:00:00,2017-02-14 13:58:48
95774,c444278834184f72b1484dfe47de7f97,8557dabbdacec1a9e250f5e70afe1eab,5,NaN,NaN,2017-02-08 00:00:00,2017-02-14 13:58:48

## customers

In [54]:
## 1. number of rows and columns
customers.shape

(99441, 5)

In [55]:
## 2. first 5 rows
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [56]:
## 3. column's names
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

In [57]:
## 4. data types
customers.dtypes

customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

In [58]:
## data conversion
## customer_zip_code_prefix

In [59]:
## 5. data preview
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [60]:
## no nulls

In [61]:
## 6. number of duplicates
customers.duplicated().sum()

np.int64(0)

In [62]:
customers["customer_id"].is_unique

True

In [63]:
customers["customer_unique_id"].is_unique

False

In [64]:
## 7. data string describtion
customers.describe(include="object")

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12832\2762111107.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  customers.describe(include="object")

,customer_id,customer_unique_id,customer_city,customer_state
count,99441,99441,99441,99441
unique,99441,96096,4119,27
top,06b8999e2fba1a1fbc88172c00ba8bc7,8d50f5eadf50201ccdcedfb9e2ac8455,sao paulo,SP
freq,1,17,15540,41746

## products

In [65]:
## 1. number of rows and columns
products.shape

(32951, 9)

In [66]:
## 2. first 5 rows
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [67]:
## 3. column's names
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

In [68]:
## 4. data types
products.dtypes

product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [69]:
## 5. data preview
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [70]:
## 6. perecent of missing values
(products.isna().sum()/len(products))*100

product_id                    0.000000
product_category_name         1.851234
product_name_lenght           1.851234
product_description_lenght    1.851234
product_photos_qty            1.851234
product_weight_g              0.006070
product_length_cm             0.006070
product_height_cm             0.006070
product_width_cm              0.006070
dtype: float64

In [71]:
def check_null_products_in_orders(
        products,order_items,check_columns,id_columns = "product_id"):
         null_products = products[products[check_columns].isnull()]
         null_ids = null_products[id_columns]
         matching_orders = order_items[order_items[id_columns].isin(null_ids)]
         print(f"===column report: {check_columns}===")
         print(f"number of products that contain null in products table: {len(null_products)}")
         print(f"number of times these products appeared in orders tables: {len(matching_orders)}")
         if len(matching_orders)> 0:
                 print("these products are sold do not drop them")
         else:
                 print("these products are not sold you can drop them")
         return matching_orders

In [72]:
columns_to_check = ["product_weight_g","product_length_cm","product_height_cm","product_width_cm","product_category_name","product_name_lenght","product_description_lenght","product_photos_qty"]
for col in columns_to_check:
    check_null_products_in_orders(products, order_items,check_columns=col)

===column report: product_weight_g===
number of products that contain null in products table: 2
number of times these products appeared in orders tables: 18
these products are sold do not drop them
===column report: product_length_cm===
number of products that contain null in products table: 2
number of times these products appeared in orders tables: 18
these products are sold do not drop them
===column report: product_height_cm===
number of products that contain null in products table: 2
number of times these products appeared in orders tables: 18
these products are sold do not drop them
===column report: product_width_cm===
number of products that contain null in products table: 2
number of times these products appeared in orders tables: 18
these products are sold do not drop them
===column report: product_category_name===
number of products that contain null in products table: 610
number of times these products appeared in orders tables: 1603
these products are sold do not drop them
===column report: product_name_lenght===
number of products that contain null in products table: 610
number of times these products appeared in orders tables: 1603
these products are sold do not drop them
===column report: product_description_lenght===
number of products that contain null in products table: 610
number of times these products appeared in orders tables: 1603
these products are sold do not drop them
===column report: product_photos_qty===
number of products that contain null in products table: 610
number of times these products appeared in orders tables: 1603
these products are sold do not drop them

In [124]:
## replace null values in product category name ----> "unkown"
## replace null values in "product_weight_g","product_length_cm","product_height_cm","product_width_cm" with the median
## replace null values in "product_name_lenght","product_description_lenght","product_photos_qty" with 0

In [74]:
# 7. number of duplicates
products.duplicated().sum()

np.int64(0)

In [75]:
products["product_id"].is_unique

True

In [76]:
products.describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [77]:
products.describe(include="object")

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12832\2778178033.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  products.describe(include="object")

                              product_id product_category_name
count                              32951                 32341
unique                             32951                    73
top     1e9e8ef04dbcff4541ed26657ea517e5       cama_mesa_banho
freq                                   1                  3029

## sallers

In [78]:
## 1. number of rows and columns
sallers.shape

(3095, 4)

In [79]:
## 2. first 5 rows
sallers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [80]:
## 3. column's names
sallers.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='str')

In [81]:
## 4. data types
sallers.dtypes

seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

In [82]:
## 5. data preview
sallers.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

In [83]:
## no nulls
## change dtype of seller_zip_code_prefix into str

In [84]:
# 6. number of duplicates
sallers.duplicated().sum()

np.int64(0)

In [85]:
sallers["seller_id"].is_unique

True

_________________________________________________________________________

## products_category

In [86]:
## 1. number of rows and columns
products_category.shape

(71, 2)

In [87]:
## 2. first 5 rows
products_category.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [88]:
## 4. data types
products_category.dtypes

product_category_name            str
product_category_name_english    str
dtype: object

In [89]:
## 5. data preview
products_category.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

In [90]:
## no nulls

In [91]:
# 6. number of duplicates
products_category.duplicated().sum()

np.int64(0)

In [92]:
sallers.describe()

       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000

In [93]:
sallers.describe(include="object")

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12832\369810671.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  sallers.describe(include="object")

                               seller_id seller_city seller_state
count                               3095        3095         3095
unique                              3095         611           23
top     3442f8959a84dea7ee197c632cb2df15   sao paulo           SP
freq                                   1         694         1849

_______________________________________________________________________________

## geolocation

In [94]:
## 1. number of rows and columns
geolocation.shape

(1000163, 5)

In [95]:
## 2. first 5 rows
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [96]:
## 4. data types
geolocation.dtypes

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

In [130]:
## convert geolocation_zip_code_prefix from int64 into str

In [97]:
## 5. data preview
geolocation.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB

In [98]:
geolocation["geolocation_zip_code_prefix"].is_unique

False

In [99]:
geolocation.describe(include="object")

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12832\2386870308.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  geolocation.describe(include="object")

       geolocation_city geolocation_state
count           1000163           1000163
unique             8011                27
top           sao paulo                SP
freq             135800            404268

In [100]:
geolocation[["geolocation_lat","geolocation_lng"]].describe()

       geolocation_lat  geolocation_lng
count     1.000163e+06     1.000163e+06
mean     -2.117615e+01    -4.639054e+01
std       5.715866e+00     4.269748e+00
min      -3.660537e+01    -1.014668e+02
25%      -2.360355e+01    -4.857317e+01
50%      -2.291938e+01    -4.663788e+01
75%      -1.997962e+01    -4.376771e+01
max       4.506593e+01     1.211054e+02

__________________________________________________________________________________

# Section 2: Data Cleaning

## Order table

In [101]:
## data type conversion
datetime_col = ["order_purchase_timestamp",
                "order_approved_at",	
                "order_delivered_carrier_date",
                "order_delivered_customer_date",	
                "order_estimated_delivery_date"]
for col in datetime_col:
    orders[col] = pd.to_datetime(orders[col])

In [102]:
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

## order_items (FACT TABLE)

In [109]:
order_items["shipping_limit_date"] = pd.to_datetime(order_items["shipping_limit_date"])

In [112]:
order_items.dtypes

order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
dtype: object

## order_reviews (FACT TABLE)

In [113]:
reviewdate_col = ["review_creation_date",
                  "review_answer_timestamp"]
for cols in reviewdate_col:
    order_reviews[cols] = pd.to_datetime(order_reviews[cols])

In [114]:
order_reviews.dtypes

review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [115]:
order_reviews["review_comment_message"] = order_reviews["review_comment_message"].fillna("customer did not leave a comment")
order_reviews["review_comment_title"] = order_reviews["review_comment_title"].fillna("review not provided")

## Customers

In [125]:
## convert dtype of customer_zip_code_prefix fro int64 to string
customers["customer_zip_code_prefix"] = customers["customer_zip_code_prefix"].astype(str)

In [127]:
customers.dtypes

customer_id                 str
customer_unique_id          str
customer_zip_code_prefix    str
customer_city               str
customer_state              str
dtype: object

In [133]:
## Convert all letters to lowercase
customers["customer_city"] = customers["customer_city"].str.lower().str.strip()

## Products

In [ ]:
## replace null values in category name with "unknown"

In [116]:
products["product_category_name"] = products["product_category_name"].fillna("unkown")

In [117]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32951 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [ ]:
# fill null values in "product_name_lenght","product_description_lenght","product_photos_qty" with 0
products_t1_nullvalues = ["product_name_lenght","product_description_lenght","product_photos_qty"]

for p in products_t1_nullvalues:
    products[p] = products[p].fillna(0)

In [121]:
products.describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32951.000000,32951.000000,32951.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,47.579527,757.213104,2.148463,2276.472488,30.815078,16.937661,23.196728
std,12.071951,637.745057,1.745732,4282.038731,16.914458,13.637554,12.079047
min,0.000000,0.000000,0.000000,0.000000,7.000000,2.000000,6.000000
25%,41.000000,326.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,584.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,961.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [122]:
# fill null values in product_weight_g	product_length_cm	product_height_cm	product_width_cm with the median of each column
products["product_weight_g"] = products["product_weight_g"].fillna(products["product_weight_g"].median())
products["product_length_cm"] = products["product_length_cm"].fillna(products["product_length_cm"].median())
products["product_height_cm"] = products["product_height_cm"].fillna(products["product_height_cm"].median())
products["product_width_cm"] = products["product_width_cm"].fillna(products["product_width_cm"].median())

In [123]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32951 non-null  str
 2   product_name_lenght         32951 non-null  float64
 3   product_description_lenght  32951 non-null  float64
 4   product_photos_qty          32951 non-null  float64
 5   product_weight_g            32951 non-null  float64
 6   product_length_cm           32951 non-null  float64
 7   product_height_cm           32951 non-null  float64
 8   product_width_cm            32951 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

## Sallers

In [128]:
## change dtype of seller_zip_code_prefix into str
sallers["seller_zip_code_prefix"] = sallers["seller_zip_code_prefix"].astype(str)

In [129]:
sallers.dtypes

seller_id                 str
seller_zip_code_prefix    str
seller_city               str
seller_state              str
dtype: object

## Geolocation

In [131]:
## convert geolocation_zip_code_prefix from int64 into str
geolocation["geolocation_zip_code_prefix"] = geolocation["geolocation_zip_code_prefix"].astype(str)

In [132]:
geolocation.dtypes

geolocation_zip_code_prefix        str
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

In [134]:
## Convert all letters to lowercase
geolocation["geolocation_city"] = geolocation["geolocation_city"].str.lower().str.strip()